documentation/docs/milestones/_category_.json, documentation/docs/milestones/milestone_one.md
=> milestone one added to DOCU

documentation/docs/testing/acceptence-testing.md
Added the acceptance testing table on the documents folder.
=> Acceptance testing

creating-front-end/src/components/Routes/ReadWrite.js, creating-front-end/src/components/Routes/temp
I worked on getting delete to work, and records now successfully read / write from only under a user ID now. However, here is an error via discord that needs to be fixed: 
because of how state works in react, and how firebase we kind of have to "wait" for the records to populate, when you refresh the page / go to it for the first time, the records arent there
however once you TYPE in the input box, the records show up. this is becuase typing triggers an onChange event, hence triggering the useEffect hook which inevetiably does a fancy react refresh and sees "oh there is records, let me populate them". however i need the hook to somehow automatically do this refresh whenever the records are there, such as after a page refreshes and the records are grabbed from firebase
=> delete works. records only populate on onChange field

creating-front-end/package-lock.json, creating-front-end/package.json, creating-front-end/public/index.html, creating-front-end/src/components/Directions.js, creating-front-end/src/components/Navbar.js, creating-front-end/src/index.js
Changes are in Directions.js, Navbar.js, index.js, and index.html
=> Added route fetching from point A to point B

creating-front-end/src/components/Navbar.js, creating-front-end/src/components/RoutePage.js, creating-front-end/src/index.js
Forgot to commit routepage. Didn't commit package lock json and hope it isn't necessary. It automatically wasn't tracked when I committed
=> Route UI updated

creating-front-end/src/components/CreateRoutePage.js, creating-front-end/src/components/Navbar.js, creating-front-end/src/components/SavedRoute.js
Saved and recent routes properly populate into DB. They are in folders /savedRoutes and /recentRoutes . These are displayed in view saved routes page, with the ability to delete as well. please ignore branch name, i connected to the wrong OM ticket. This should be OM-76 which was pretty much route cleanup
=> Saved / Recent routes, create route

creating-front-end/src/components/CreateRoutePage.js, creating-front-end/src/components/SavedRoute.js
User can still save and run route to get either recent routes populated or saved routes (where they give it a name) populated. The street address drop down from maps grabs the street address as well as (long, lat) from the maps api. This saves the data both address and (lat, long) to firebase. However it only shows street address when in the "saved routes" screen for obvious user reasons / minimalism. However now you can read from the db both address and (lat, long).
=> data from api saves to fb

creating-front-end/src/components/CreateRoutePage.js, creating-front-end/src/components/LocationBox.js, creating-front-end/src/components/MapView.js
When a user creates a route and clicks run, it takes them to the mapview populated with directions. location list created in mapview so a user can see both the list and the map ui
you can click on a location within the routes list to delete it
locations automatically update and display the directions
user can still go to mapview and enter places manually, or they can create a route, save it, and run it from the create route screen
=> Om 87/crui to mapview

.github/workflows/firebase-hosting-merge.yml
=> removed /build

creating-front-end/src/components/SavedRoute.js
user can now click button "load" from saved routes page to load a previous route into the mapview.
=> user can load a saved route into mapview

creating-front-end/package.json, creating-front-end/src/components/Login.js, creating-front-end/src/components/Navbar.js, creating-front-end/src/components/Signup.js, creating-front-end/src/index.js
Added sign up/login button routing to both sign up and login page.
=> tesitng gh pages

creating-front-end/src/components/CreateRoutePage.js, creating-front-end/src/components/createRoutePage.css
Created UI to both allow a user to input arrival time and time spent at each location. UI ONLY, no firebase yet
=> Om 54/crui arrival time

README.md, documentation/docs/development-plan/schedule.md, documentation/docs/system-architecture/design.md
=> Om 70/documentation revision

creating-front-end/src/components/MapView.js
This optimization is as follows: The list of destinations that the user enters is sorted by distance from the destination to the user's current location. The Haversine formula is used to calculate the distance between the user's current location and the destination in the list. This effectively gives a sorted array of destinations where lower indices are destinations closest to the users location. When the DirectionService.route is called, it grabs this sorted list and displays the route in order on the map.
=> Added destination sort and optimization

creating-front-end/src/components/LocationBox.js
Changed delete locations to delete button
=> Order of locations

creating-front-end/package-lock.json, creating-front-end/src/components/MapView.js
All that has been edited in the MapView component to fix this bug was the automatic route updater that shows the route when the user enters at least 2 destinations. Further examination as to why the route updater not being in the code caused the markers to show incorrectly will be required.
=> Fixed markers not showing correct order / Added automatic route update

creating-front-end/src/components/CreateRoutePage.js
=> fixed input needing to be put in twice on create route ui

creating-front-end/src/components/Login.js, creating-front-end/src/components/Signup.js
function findUserIdByEmail should be changed to find the user based on the email instead of the userID. To fix this issue, you can modify the findUserIdByEmail function to search for the user based on the email.
First, you need to change your database structure to store user email addresses in a separate node called emails, indexed by their userId. This will make it easy to query the user's email address by their userId.
=> email is now saved to acc so I can see for friends

creating-front-end/src/components/SavedRoute.js
Styled buttons to look better on mobile for the saved routes page
=> mobile styling saved routes page

creating-front-end/src/components/CreateRoutePage.js
Added delete buttons on route page
Also added clear button at the bottom of page
=> Added some QOL changes to createroute page

creating-front-end/package-lock.json, creating-front-end/src/components/Profile.js
With these changes, the input field and button used for sending friend requests will be responsive across different screen sizes
=> Added responsive design to Add Friend input in Profile Screen

creating-front-end/src/components/Login.js, creating-front-end/src/components/Login.test.js, creating-front-end/src/components/Signup.js, creating-front-end/src/components/Signup.test.js, documentation/docs/test-report/_category_.json, documentation/docs/test-report/acceptence-testing-report.md, documentation/docs/test-report/integration-testing-report.md, documentation/docs/test-report/unit-testing-report.md
Added a few changes in Signup page as well as Docusaurus to include the Test Report
=> Signup and Login testing in Jest 

creating-front-end/src/components/Directions.js, creating-front-end/src/components/testing/App.test.js, creating-front-end/src/components/testing/Directions.test.js, creating-front-end/src/components/testing/Login.test.js, creating-front-end/src/components/testing/Navbar.test.js, creating-front-end/src/components/testing/Signup.test.js, creating-front-end/src/components/testing/index.test.js, documentation/docs/test-report/unit-testing-report.md, documentation/package-lock.json
Fixed jest.mock paths, added App.test.js, index.test.js, navbar.test.js, directions.test.js. and updated test report
=> Om 108/jest testing

creating-front-end/cypress.config.js, creating-front-end/cypress/e2e/1-getting-started/todo.cy.js, creating-front-end/cypress/e2e/2-advanced-examples/actions.cy.js, creating-front-end/cypress/e2e/2-advanced-examples/aliasing.cy.js, creating-front-end/cypress/e2e/2-advanced-examples/assertions.cy.js, creating-front-end/cypress/e2e/2-advanced-examples/connectors.cy.js, creating-front-end/cypress/e2e/2-advanced-examples/cookies.cy.js, creating-front-end/cypress/e2e/2-advanced-examples/cypress_api.cy.js, creating-front-end/cypress/e2e/2-advanced-examples/files.cy.js, creating-front-end/cypress/e2e/2-advanced-examples/location.cy.js, creating-front-end/cypress/e2e/2-advanced-examples/misc.cy.js, creating-front-end/cypress/e2e/2-advanced-examples/navigation.cy.js, creating-front-end/cypress/e2e/2-advanced-examples/network_requests.cy.js, creating-front-end/cypress/e2e/2-advanced-examples/querying.cy.js, creating-front-end/cypress/e2e/2-advanced-examples/spies_stubs_clocks.cy.js, creating-front-end/cypress/e2e/2-advanced-examples/storage.cy.js, creating-front-end/cypress/e2e/2-advanced-examples/traversal.cy.js, creating-front-end/cypress/e2e/2-advanced-examples/utilities.cy.js, creating-front-end/cypress/e2e/2-advanced-examples/viewport.cy.js, creating-front-end/cypress/e2e/2-advanced-examples/waiting.cy.js, creating-front-end/cypress/e2e/2-advanced-examples/window.cy.js, creating-front-end/cypress/e2e/Authenticaiton.cy.js, creating-front-end/cypress/e2e/CreateRoute.cy.js, creating-front-end/cypress/support/commands.js, creating-front-end/cypress/support/component-index.html, creating-front-end/cypress/support/component.js, creating-front-end/cypress/support/e2e.js, creating-front-end/package-lock.json, creating-front-end/package.json, creating-front-end/src/components/testingAcceptance/Authentication.cy.js
=> Basic User Authentication and CreateRoute Testing

README.md, documentation/docs/development-plan/activities.md, documentation/docs/development-plan/development-environment.md, documentation/docs/development-plan/tasks.md
More corrections of React Native -> React JS language, etc.
=> Software development update docs

documentation/docs/test-report/integration-testing-report.md, documentation/docs/test-report/unit-testing-report.md
There were two integration tests in the unit test report. I moved them to the Integration test report
=> Moved Integration tests from unit test

creating-front-end/src/components/SavedRoute.js
created function to find user email by taking in id.
made font smaller and gray to stand out less
=> Sharing routes
